### ISSUE TITLE
Invalid Status attributes appendlimit

### ISSUE THREAD

**Issue by luckman212** [gonejack/import-mail#1]
Hi @gonejack 

I am sorry to bother you with an issue. But this project is exactly something I was looking for, so hoping maybe you have an answer. 

I installed your tool, and am trying to import a single `.eml` file (299 Kb) to my IMAP server (FastMail).

I have the correct username/password/port I am sure (I can verify communication wth the server).

Upon running the command, I am getting `Invalid Status attributes appendlimit`:

```shell
$ import-mail --host imap.fastmail.com --port 993 --username me@mydomain.com --password mySecretPwd Test.eml
2021/10/07 11:06:17 Invalid Status attributes appendlimit
```

I assume this is because the server is returning an unexpected response to `queryAppendLimit()` 

https://github.com/gonejack/import-mail/blob/31e94811980be78af3321c0bcb4f13adfad479f5/cmd/cmd.go#L126

Would you possibly be able to guide me on removing this check? Or how to adjust the code to be more tolerant of responses here? I tried `--append-limit 0` but that did not work.

**Comment by gonejack** [comment]
Hi, @luckman212  could you try this new release to see if this error still exists.

```
go get github.com/gonejack/import-mail@v1.0.1
```

**Comment by luckman212** [comment]
🚀 🚀 🚀 
Amazing!
Yes it works perfectly now with v1.0.1 @gonejack 
Thank you so much for this tool. It is so much nicer to be able to import a few .EML files instead of downloading an entire mailbox in Thunderbird just to import 1 email. Nice work!
